YAOS_BUSINESS_SHARED_SOURCES += \
    src/runtime/Templates.cpp \
    src/runtime/CronService.cpp \
    src/runtime/ApprovalStore.cpp \
    src/runtime/AutomationStore.cpp \
    src/runtime/EventLog.cpp \
    src/runtime/HeartbeatService.cpp \
    src/runtime/NotificationCenter.cpp \
    src/runtime/PluginRegistry.cpp \
    src/runtime/SkillRegistry.cpp \
    src/runtime/StructuredLog.cpp \
    src/runtime/ResourceCatalog.cpp \
    src/runtime/RuntimeSerialization.cpp \
    src/runtime/RuntimeCore.cpp \
    src/runtime/SubagentManager.cpp \
    src/runtime/TaskStore.cpp \
    src/runtime/MCPManager.cpp \
    src/runtime/LocalRuntimeClient.cpp \
    src/runtime/RemoteRuntimeClient.cpp \
    src/runtime/RuntimeServiceSupport.cpp \
    src/providers/EchoProvider.cpp \
    src/providers/OpenAICompatibleProvider.cpp \
    src/providers/AnthropicProvider.cpp \
    src/providers/ProviderOAuth.cpp \
    src/providers/ProviderRegistry.cpp \
    src/providers/ProviderFactory.cpp \
    src/channels/TelegramChannel.cpp \
    src/channels/SlackChannel.cpp \
    src/channels/MatrixChannel.cpp \
    src/channels/EmailChannel.cpp \
    src/channels/QQChannel.cpp \
    src/channels/FeishuChannel.cpp \
    src/channels/WhatsAppChannel.cpp \
    src/channels/DingTalkChannel.cpp \
    src/channels/MochatChannel.cpp \
    src/channels/DiscordChannel.cpp \
    src/channels/ChannelManager.cpp \
    src/agent/ToolRegistry.cpp \
    src/agent/tools/FileTools.cpp \
    src/agent/tools/WebTools.cpp \
    src/agent/tools/ExecTool.cpp \
    src/agent/tools/PluginTool.cpp \
    src/agent/tools/MessageTool.cpp \
    src/agent/tools/SpawnTool.cpp \
    src/agent/tools/CronTool.cpp \
    src/agent/tools/MCPCallTool.cpp \
    src/agent/tools/MCPProxyTool.cpp \
    src/agent/MemoryStore.cpp \
    src/memory/LayeredMemoryExporter.cpp \
    src/memory/LocalMemoryRetriever.cpp \
    src/memory/LocalMemoryIngestor.cpp \
    src/memory/MemoryRuntimeFactory.cpp \
    src/memory/MemoryServiceSupport.cpp \
    src/memory/RemoteMemoryBackends.cpp \
    src/memory/RemoteMemoryClient.cpp \
    src/memory/RemoteMemoryProtocol.cpp \
    src/memory/SqliteFactStore.cpp \
    src/memory/SqliteConversationStore.cpp \
    src/agent/ContextBuilder.cpp \
    src/agent/AgentLoop.cpp

YAOS_BUSINESS_SHARED_HEADERS += \
    src/runtime/Templates.h \
    src/runtime/CronService.h \
    src/runtime/ApprovalStore.h \
    src/runtime/AutomationStore.h \
    src/runtime/EventLog.h \
    src/runtime/HeartbeatService.h \
    src/runtime/NotificationCenter.h \
    src/runtime/PluginRegistry.h \
    src/runtime/SkillRegistry.h \
    src/runtime/StructuredLog.h \
    src/runtime/ResourceCatalog.h \
    src/runtime/RuntimeSerialization.h \
    src/runtime/RuntimeCore.h \
    src/runtime/RuntimeTypes.h \
    src/runtime/SubagentManager.h \
    src/runtime/TaskStore.h \
    src/runtime/MCPManager.h \
    src/runtime/LocalRuntimeClient.h \
    src/runtime/RemoteRuntimeClient.h \
    src/runtime/RuntimeServiceSupport.h \
    src/agent/Types.h \
    src/providers/LLMProvider.h \
    src/providers/EchoProvider.h \
    src/providers/OpenAICompatibleProvider.h \
    src/providers/AnthropicProvider.h \
    src/providers/ProviderOAuth.h \
    src/providers/ProviderRegistry.h \
    src/providers/ProviderFactory.h \
    src/channels/Channel.h \
    src/channels/ChannelHttp.h \
    src/channels/TelegramChannel.h \
    src/channels/SlackChannel.h \
    src/channels/MatrixChannel.h \
    src/channels/EmailChannel.h \
    src/channels/QQChannel.h \
    src/channels/FeishuChannel.h \
    src/channels/WhatsAppChannel.h \
    src/channels/DingTalkChannel.h \
    src/channels/MochatChannel.h \
    src/channels/DiscordChannel.h \
    src/channels/ChannelManager.h \
    src/agent/Tool.h \
    src/agent/ToolRegistry.h \
    src/agent/tools/FileTools.h \
    src/agent/tools/WebTools.h \
    src/agent/tools/ExecTool.h \
    src/agent/tools/PluginTool.h \
    src/agent/tools/MessageTool.h \
    src/agent/tools/SpawnTool.h \
    src/agent/tools/CronTool.h \
    src/agent/tools/MCPCallTool.h \
    src/agent/tools/MCPProxyTool.h \
    src/agent/MemoryStore.h \
    src/memory/LayeredMemoryExporter.h \
    src/memory/LocalMemoryRetriever.h \
    src/memory/LocalMemoryIngestor.h \
    src/memory/MemoryRuntimeFactory.h \
    src/memory/MemoryBackend.h \
    src/memory/MemoryServiceSupport.h \
    src/memory/RemoteMemoryBackends.h \
    src/memory/RemoteMemoryClient.h \
    src/memory/RemoteMemoryProtocol.h \
    src/memory/SqliteFactStore.h \
    src/memory/SqliteConversationStore.h \
    src/agent/ContextBuilder.h \
    src/agent/AgentLoop.h

YAOS_BUSINESS_APP_SOURCES += \
    src/app/ApplicationController.cpp \
    src/config/DelegationTemplateExchange.cpp \
    src/control/ControlHttpServer.cpp \
    src/control/ControlServiceCore.cpp \
    src/daemon/DaemonRuntimeClient.cpp \
    src/runtime/ExtensionCatalog.cpp \
    src/runtime/RuntimeFacade.cpp \
    src/runtime/RuntimeClientFacade.cpp \
    src/runtime/RuntimeHttpServer.cpp \
    src/memory/MemoryHttpServer.cpp \
    src/memory/MemoryServiceCore.cpp

YAOS_BUSINESS_APP_HEADERS += \
    src/app/ApplicationController.h \
    src/config/DelegationTemplateExchange.h \
    src/control/ControlHttpServer.h \
    src/control/ControlServiceCore.h \
    src/daemon/DaemonRuntimeClient.h \
    src/runtime/ExtensionCatalog.h \
    src/runtime/RuntimeFacade.h \
    src/runtime/RuntimeClientFacade.h \
    src/runtime/RuntimeHttpServer.h \
    src/memory/MemoryHttpServer.h \
    src/memory/MemoryServiceCore.h
