import re

filepath = r'd:\GITHUB\YAOS\src\ui\StudioBridge.cpp'

with open(filepath, 'rb') as f:
    raw = f.read()

content = raw.decode('utf-8', errors='replace')

# ===== PATCH 1: providerAuthStatus =====
old1 = (
    'QVariantMap StudioBridge::providerAuthStatus(const QString &providerId) {\r\n'
    '    const QString normalized = normalizedProviderId(providerId);\r\n'
    '    const config::ProviderConfig *provider = providerConfigById(m_config, normalized);\r\n'
    '    if (!provider) {\r\n'
    '        return QVariantMap{\r\n'
    '            {QStringLiteral("ok"), false},\r\n'
    '            {QStringLiteral("error"), QStringLiteral("provider config not found")},\r\n'
    '            {QStringLiteral("providerId"), normalized}\r\n'
    '        };\r\n'
    '    }\r\n'
    '\r\n'
    '    // Keep the QML-facing status getter side-effect free. Provider cards call this\r\n'
    '    // while a Repeater is constructing delegates, and mutating config from here can\r\n'
    '    // re-enter model refresh during creation.\r\n'
    '    providers::ProviderOAuthResult result = providers::providerOAuthStatus(normalized, *provider);\r\n'
    '    QVariantMap map;\r\n'
    '    const auto it = m_oauthSessions.constFind(normalized);\r\n'
    '    if (it != m_oauthSessions.constEnd() && it.value()) {\r\n'
    '        const PendingOAuthSession *session = it.value().data();\r\n'
    '        result.pending = !session->complete;\r\n'
    '        result.mode = session->mode;\r\n'
    '        result.authUrl = session->authUrl;\r\n'
    '        if (!session->error.trimmed().isEmpty()) {\r\n'
    '            result.error = session->error;\r\n'
    '        }\r\n'
    '        if (session->complete) {\r\n'
    '            result.pending = false;\r\n'
    '            if (!session->success && result.error.trimmed().isEmpty()) {\r\n'
    '                result.error = QStringLiteral("OAuth login did not complete successfully.");\r\n'
    '            }\r\n'
    '        }\r\n'
    '    }\r\n'
    '    map = result.toVariantMap();\r\n'
    '    if (it != m_oauthSessions.constEnd() && it.value()) {\r\n'
    '        if (!it.value()->redirectUri.trimmed().isEmpty()) {\r\n'
    '            map.insert(QStringLiteral("redirectUri"), it.value()->redirectUri);\r\n'
    '        }\r\n'
    '        if (!it.value()->callbackUrl.trimmed().isEmpty()) {\r\n'
    '            map.insert(QStringLiteral("callbackUrl"), it.value()->callbackUrl);\r\n'
    '        }\r\n'
    '    }\r\n'
    '    return map;\r\n'
    '}'
)

new1 = (
    'QVariantMap StudioBridge::providerAuthStatus(const QString &providerId) {\r\n'
    '    const QString normalized = normalizedProviderId(providerId);\r\n'
    '\r\n'
    '    // Keep the QML-facing status getter side-effect free. Provider cards call this\r\n'
    '    // while a Repeater is constructing delegates, and mutating config from here can\r\n'
    '    // re-enter model refresh during creation.\r\n'
    '    std::shared_ptr<IStudioBackend> backend;\r\n'
    '    {\r\n'
    '        QMutexLocker locker(&m_backendMutex);\r\n'
    '        backend = m_backend;\r\n'
    '    }\r\n'
    '    QVariantMap map = backend\r\n'
    '        ? backend->providerAuthStatus(m_config, normalized)\r\n'
    '        : QVariantMap{\r\n'
    '              {QStringLiteral("ok"), false},\r\n'
    '              {QStringLiteral("error"), QStringLiteral("runtime backend is not initialized")},\r\n'
    '              {QStringLiteral("providerId"), normalized}\r\n'
    '          };\r\n'
    '\r\n'
    '    // Overlay local browser OAuth session state (loopback listener, authUrl, etc.)\r\n'
    '    const auto it = m_oauthSessions.constFind(normalized);\r\n'
    '    if (it != m_oauthSessions.constEnd() && it.value()) {\r\n'
    '        const PendingOAuthSession *session = it.value().data();\r\n'
    '        map.insert(QStringLiteral("pending"), !session->complete);\r\n'
    '        map.insert(QStringLiteral("mode"), session->mode);\r\n'
    '        if (!session->authUrl.trimmed().isEmpty()) {\r\n'
    '            map.insert(QStringLiteral("authUrl"), session->authUrl);\r\n'
    '        }\r\n'
    '        if (!session->error.trimmed().isEmpty()) {\r\n'
    '            map.insert(QStringLiteral("error"), session->error);\r\n'
    '        }\r\n'
    '        if (session->complete) {\r\n'
    '            map.insert(QStringLiteral("pending"), false);\r\n'
    '            if (!session->success && map.value(QStringLiteral("error")).toString().trimmed().isEmpty()) {\r\n'
    '                map.insert(QStringLiteral("error"), QStringLiteral("OAuth login did not complete successfully."));\r\n'
    '            }\r\n'
    '        }\r\n'
    '        if (!it.value()->redirectUri.trimmed().isEmpty()) {\r\n'
    '            map.insert(QStringLiteral("redirectUri"), it.value()->redirectUri);\r\n'
    '        }\r\n'
    '        if (!it.value()->callbackUrl.trimmed().isEmpty()) {\r\n'
    '            map.insert(QStringLiteral("callbackUrl"), it.value()->callbackUrl);\r\n'
    '        }\r\n'
    '    }\r\n'
    '    return map;\r\n'
    '}'
)

if old1 in content:
    content = content.replace(old1, new1, 1)
    print("PATCH 1 (providerAuthStatus): applied")
else:
    print("PATCH 1 (providerAuthStatus): NOT FOUND")

# ===== PATCH 2: pollProviderOAuth — device flow poll changed to backend =====
old2 = (
    'QVariantMap StudioBridge::pollProviderOAuth(const QString &providerId) {\r\n'
    '    const QString normalized = normalizedProviderId(providerId);\r\n'
    '    auto sessionIt = m_oauthSessions.find(normalized);\r\n'
    '    if (sessionIt != m_oauthSessions.end() && sessionIt.value()) {\r\n'
    '        return providerAuthStatus(normalized);\r\n'
    '    }\r\n'
    '\r\n'
    '    config::Config nextConfig = m_config;\r\n'
    '    config::ProviderConfig *provider = providerConfigById(nextConfig, normalized);\r\n'
    '    if (!provider) {\r\n'
    '        return QVariantMap{\r\n'
    '            {QStringLiteral("ok"), false},\r\n'
    '            {QStringLiteral("error"), QStringLiteral("provider config not found")}\r\n'
    '        };\r\n'
    '    }\r\n'
    '\r\n'
    '    providers::ProviderOAuthResult result = providers::pollDeviceFlow(normalized, *provider);\r\n'
    '    if (result.changed) {\r\n'
    '        *provider = result.config;\r\n'
    '        if (!config::ConfigLoader::save(nextConfig)) {\r\n'
    '            result.ok = false;\r\n'
    '            result.error = QStringLiteral("failed to persist OAuth state");\r\n'
    '        } else {\r\n'
    '            if (result.loggedIn) {\r\n'
    '                QMutexLocker locker(&m_backendMutex);\r\n'
    '                if (m_backend) {\r\n'
    '                    m_backend->reloadFromDisk();\r\n'
    '                }\r\n'
    '            }\r\n'
    '            m_config = nextConfig;\r\n'
    '            refreshAll();\r\n'
    '        }\r\n'
    '    }\r\n'
    '\r\n'
    '    if (result.ok && result.loggedIn) {\r\n'
    '        emit toastRequested(QStringLiteral("OAuth connected"),\r\n'
    '                            QStringLiteral("Provider %1 has been authorized.").arg(normalized),\r\n'
    '                            QStringLiteral("success"));\r\n'
    '    } else if (!result.ok && !result.error.trimmed().isEmpty()) {\r\n'
    '        emit toastRequested(QStringLiteral("OAuth failed"),\r\n'
    '                            result.error,\r\n'
    '                            QStringLiteral("warning"));\r\n'
    '    }\r\n'
    '    return result.toVariantMap();\r\n'
    '}'
)

new2 = (
    'QVariantMap StudioBridge::pollProviderOAuth(const QString &providerId) {\r\n'
    '    const QString normalized = normalizedProviderId(providerId);\r\n'
    '    // If there is an active browser session, just return its status.\r\n'
    '    auto sessionIt = m_oauthSessions.find(normalized);\r\n'
    '    if (sessionIt != m_oauthSessions.end() && sessionIt.value()) {\r\n'
    '        return providerAuthStatus(normalized);\r\n'
    '    }\r\n'
    '\r\n'
    '    std::shared_ptr<IStudioBackend> backend;\r\n'
    '    {\r\n'
    '        QMutexLocker locker(&m_backendMutex);\r\n'
    '        backend = m_backend;\r\n'
    '    }\r\n'
    '    if (!backend) {\r\n'
    '        return QVariantMap{\r\n'
    '            {QStringLiteral("ok"), false},\r\n'
    '            {QStringLiteral("error"), QStringLiteral("runtime backend is not initialized")}\r\n'
    '        };\r\n'
    '    }\r\n'
    '\r\n'
    '    const QVariantMap result = backend->pollProviderDeviceFlow(&m_config, normalized);\r\n'
    '    if (result.value(QStringLiteral("configChanged")).toBool()) {\r\n'
    '        m_configMap = m_config.toJson().toVariantMap();\r\n'
    '        emit configChanged();\r\n'
    '        refreshAll();\r\n'
    '    }\r\n'
    '    const bool loggedIn = result.value(QStringLiteral("loggedIn")).toBool();\r\n'
    '    const bool ok = result.value(QStringLiteral("ok")).toBool();\r\n'
    '    const QString error = result.value(QStringLiteral("error")).toString();\r\n'
    '    if (ok && loggedIn) {\r\n'
    '        emit toastRequested(QStringLiteral("OAuth connected"),\r\n'
    '                            QStringLiteral("Provider %1 has been authorized.").arg(normalized),\r\n'
    '                            QStringLiteral("success"));\r\n'
    '    } else if (!ok && !error.trimmed().isEmpty()) {\r\n'
    '        emit toastRequested(QStringLiteral("OAuth failed"),\r\n'
    '                            error,\r\n'
    '                            QStringLiteral("warning"));\r\n'
    '    }\r\n'
    '    return result;\r\n'
    '}'
)

if old2 in content:
    content = content.replace(old2, new2, 1)
    print("PATCH 2 (pollProviderOAuth): applied")
else:
    print("PATCH 2 (pollProviderOAuth): NOT FOUND")

# ===== PATCH 3: refreshProviderOAuth — changed to backend =====
old3 = (
    'QVariantMap StudioBridge::refreshProviderOAuth(const QString &providerId) {\r\n'
    '    const QString normalized = normalizedProviderId(providerId);\r\n'
    '    config::Config nextConfig = m_config;\r\n'
    '    config::ProviderConfig *provider = providerConfigById(nextConfig, normalized);\r\n'
    '    if (!provider) {\r\n'
    '        return QVariantMap{\r\n'
    '            {QStringLiteral("ok"), false},\r\n'
    '            {QStringLiteral("error"), QStringLiteral("provider config not found")}\r\n'
    '        };\r\n'
    '    }\r\n'
    '\r\n'
    '    providers::ProviderOAuthResult result = providers::refreshProviderTokens(normalized, *provider);\r\n'
    '    if (result.changed) {\r\n'
    '        *provider = result.config;\r\n'
    '        if (!config::ConfigLoader::save(nextConfig)) {\r\n'
    '            result.ok = false;\r\n'
    '            result.error = QStringLiteral("failed to persist refreshed credentials");\r\n'
    '        } else {\r\n'
    '            {\r\n'
    '                QMutexLocker locker(&m_backendMutex);\r\n'
    '                if (m_backend) {\r\n'
    '                    m_backend->reloadFromDisk();\r\n'
    '                }\r\n'
    '            }\r\n'
    '            m_config = nextConfig;\r\n'
    '            refreshAll();\r\n'
    '        }\r\n'
    '    }\r\n'
    '\r\n'
    '    emit toastRequested(result.ok ? QStringLiteral("OAuth refreshed")\r\n'
    '                                  : QStringLiteral("OAuth refresh failed"),\r\n'
    '                        result.ok ? QStringLiteral("Provider %1 tokens have been refreshed.").arg(normalized)\r\n'
    '                                  : result.error,\r\n'
    '                        result.ok ? QStringLiteral("success") : QStringLiteral("warning"));\r\n'
    '    return result.toVariantMap();\r\n'
    '}'
)

new3 = (
    'QVariantMap StudioBridge::refreshProviderOAuth(const QString &providerId) {\r\n'
    '    const QString normalized = normalizedProviderId(providerId);\r\n'
    '\r\n'
    '    std::shared_ptr<IStudioBackend> backend;\r\n'
    '    {\r\n'
    '        QMutexLocker locker(&m_backendMutex);\r\n'
    '        backend = m_backend;\r\n'
    '    }\r\n'
    '    if (!backend) {\r\n'
    '        return QVariantMap{\r\n'
    '            {QStringLiteral("ok"), false},\r\n'
    '            {QStringLiteral("error"), QStringLiteral("runtime backend is not initialized")}\r\n'
    '        };\r\n'
    '    }\r\n'
    '\r\n'
    '    const QVariantMap result = backend->refreshProviderOAuth(&m_config, normalized);\r\n'
    '    if (result.value(QStringLiteral("configChanged")).toBool()) {\r\n'
    '        m_configMap = m_config.toJson().toVariantMap();\r\n'
    '        emit configChanged();\r\n'
    '        refreshAll();\r\n'
    '    }\r\n'
    '    const bool ok = result.value(QStringLiteral("ok")).toBool();\r\n'
    '    const QString error = result.value(QStringLiteral("error")).toString();\r\n'
    '    emit toastRequested(ok ? QStringLiteral("OAuth refreshed")\r\n'
    '                           : QStringLiteral("OAuth refresh failed"),\r\n'
    '                        ok ? QStringLiteral("Provider %1 tokens have been refreshed.").arg(normalized)\r\n'
    '                           : error,\r\n'
    '                        ok ? QStringLiteral("success") : QStringLiteral("warning"));\r\n'
    '    return result;\r\n'
    '}'
)

if old3 in content:
    content = content.replace(old3, new3, 1)
    print("PATCH 3 (refreshProviderOAuth): applied")
else:
    print("PATCH 3 (refreshProviderOAuth): NOT FOUND")

# ===== PATCH 4: logoutProviderOAuth — changed to backend =====
old4 = (
    'bool StudioBridge::logoutProviderOAuth(const QString &providerId) {\r\n'
    '    const QString normalized = normalizedProviderId(providerId);\r\n'
    '    closeOAuthSession(normalized);\r\n'
    '\r\n'
    '    config::Config nextConfig = m_config;\r\n'
    '    config::ProviderConfig *provider = providerConfigById(nextConfig, normalized);\r\n'
    '    if (!provider) {\r\n'
    '        return false;\r\n'
    '    }\r\n'
    '\r\n'
    '    *provider = providers::clearOAuthState(normalized, *provider);\r\n'
    '    if (!config::ConfigLoader::save(nextConfig)) {\r\n'
    '        emit toastRequested(QStringLiteral("Logout failed"),\r\n'
    '                            QStringLiteral("Unable to clear stored OAuth credentials."),\r\n'
    '                            QStringLiteral("warning"));\r\n'
    '        return false;\r\n'
    '    }\r\n'
    '\r\n'
    '    {\r\n'
    '        QMutexLocker locker(&m_backendMutex);\r\n'
    '        if (m_backend) {\r\n'
    '            m_backend->reloadFromDisk();\r\n'
    '        }\r\n'
    '    }\r\n'
    '    m_config = nextConfig;\r\n'
    '    refreshAll();\r\n'
    '    emit toastRequested(QStringLiteral("OAuth cleared"),\r\n'
    '                        QStringLiteral("Provider %1 has been signed out.").arg(normalized),\r\n'
    '                        QStringLiteral("neutral"));\r\n'
    '    return true;\r\n'
    '}'
)

new4 = (
    'bool StudioBridge::logoutProviderOAuth(const QString &providerId) {\r\n'
    '    const QString normalized = normalizedProviderId(providerId);\r\n'
    '    closeOAuthSession(normalized);\r\n'
    '\r\n'
    '    std::shared_ptr<IStudioBackend> backend;\r\n'
    '    {\r\n'
    '        QMutexLocker locker(&m_backendMutex);\r\n'
    '        backend = m_backend;\r\n'
    '    }\r\n'
    '    if (!backend) {\r\n'
    '        emit toastRequested(QStringLiteral("Logout failed"),\r\n'
    '                            QStringLiteral("runtime backend is not initialized"),\r\n'
    '                            QStringLiteral("warning"));\r\n'
    '        return false;\r\n'
    '    }\r\n'
    '\r\n'
    '    const QVariantMap result = backend->logoutProviderOAuth(&m_config, normalized);\r\n'
    '    if (!result.value(QStringLiteral("ok")).toBool()) {\r\n'
    '        const QString body = result.value(QStringLiteral("error"),\r\n'
    '                                          QStringLiteral("Unable to clear stored OAuth credentials.")).toString();\r\n'
    '        emit toastRequested(QStringLiteral("Logout failed"), body, QStringLiteral("warning"));\r\n'
    '        return false;\r\n'
    '    }\r\n'
    '    if (result.value(QStringLiteral("configChanged")).toBool()) {\r\n'
    '        m_configMap = m_config.toJson().toVariantMap();\r\n'
    '        emit configChanged();\r\n'
    '        refreshAll();\r\n'
    '    }\r\n'
    '    emit toastRequested(QStringLiteral("OAuth cleared"),\r\n'
    '                        QStringLiteral("Provider %1 has been signed out.").arg(normalized),\r\n'
    '                        QStringLiteral("neutral"));\r\n'
    '    return true;\r\n'
    '}'
)

if old4 in content:
    content = content.replace(old4, new4, 1)
    print("PATCH 4 (logoutProviderOAuth): applied")
else:
    print("PATCH 4 (logoutProviderOAuth): NOT FOUND")

with open(filepath, 'wb') as f:
    f.write(content.encode('utf-8'))

print("Done.")
